<div id = footer>
		<footer class="footer">
			<p>COS10026</p>
			<p>&#169; Swinburne University of Technology</p>
			<p>Group Assignment Part 1</p><br>
			<a href="mailto:103831724@student.swin.edu.au">103831724@student.swin.edu.au</a>
			<a href="mailto:103986022@student.swin.edu.au">103986022@student.swin.edu.au</a>
			<a href="mailto:1103843949@student.swin.edu.au">1103843949@student.swin.edu.au</a>
			<a href="mailto:100595852@student.swin.edu.au">100595852@student.swin.edu.au</a>
			<a href="mailto:1103500118@student.swin.edu.au">1103500118@student.swin.edu.au</a>		
		</footer>
	</div>