<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="COS10026 Mark Quiz" />
        <meta name="keywords" content="PHP, MySQL" />
        <title>Retrieving records to HTML</title>
    </head>
    <body>
        <h1>
            Creating Web Applications - Lab10
        </h1>
    <?php
    require_once("settings.php"); //connection info

    $conn = @mysqli_connect($host, $user, $pwd, $sql_db);

    //checks if connection is successful
    if(!$conn)
    {
        //Displays an error message
        echo "<p>Database connection faliure</p>"; //not in production script
    }
    else
    {
        //takes in the data generated by the quiz form
        $studentid = htmlspecialchars(trim($_POST["studentid"]));
        $firstname = htmlspecialchars(trim($_POST["firstname"]));
        $lastname = htmlspecialchars(trim($_POST["lastname"]));
        $textquestion = htmlspecialchars(trim($_POST["textquestion"]));
        $multiplechoice1 = htmlspecialchars(trim($_POST["multiplechoice1"]));
        $dropdownmultichoice = htmlspecialchars(trim($_POST["dropdownmultichoice"]));
        $multicheckbox = $_POST["multicheckbox"];
        $numericalQuestion = htmlspecialchars(trim($_POST["numericalQuestion"]));

        $errMsg = "";

        //checks that the student ID has been set and is in the required format.
        if($studentid == "")
        {
            $errMsg .= "<p>You must enter your first name.</p>";
        }
        else if (!preg_match("/^[0-9]{7}$|^[0-9]{10}$/", $studentid))
        {
            $errMsg .= "<p>You must enter 7 or 10 numbers for your student ID.</p>";
        }
        
        //checks that the first name is in the required format
        if($firstname == "")
        {
            $errMsg .= "<p>You must enter your first name.</p>";
        }
        else if (!preg_match("/^[a-zA-Z- ]{0,30}$/", $firstname))
        {
            $errMsg .= "<p>Only alpha letters allowed in your first name.</p>";
        }
        
        //checks that the lastname has been set and is in the required format.
        if($lastname == "")
        {
            $errMsg .= "<p>You must enter your last name.</p>";
        }
        else if (!preg_match("/^[a-zA-Z\-]{0,30}$/", $lastname))
        {
            $errMsg .= "<p>Only alpha letters and hyphens allowed in your last name.</p>";
        }

        //Checks that all questions in the form have been filled in.
        if (($textquestion == "")
            || ($multiplechoice1 == "")
            || ($dropdownmultichoice == "")
            || ($multicheckbox == ""))
        {
            $errMsg .= "<p>Please fill in every field in the quiz form.</p>";
        }

        //marks the quiz
        $marks = 0.0;
        $totalmarks = 5;

        echo $multiplechoice1;

        if ($textquestion == "")
            $marks++;
        if ($multiplechoice1 == "a")
            $marks++;
        if ($dropdownmultichoice == "b")
            $marks++;
        if ($multicheckbox == "")
            $marks++;
        if ($numericalQuestion == "")
            $marks++;

        $score = ($marks/$totalmarks)*100;

        //check if the table exists, create it if not, mptid INT NOT NULL, score INT NOT NULL);
        $sql_table="attempts";
        $query = "SELECT attemptid FROM attempts";
        $result = mysqli_query($conn, $query);
        if (!$result)
        {
            $query = "CREATE TABLE attempts (attempt_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, date_time datetime NOT NULL, firstname VARCHAR(30) NOT NULL, lastname VARCHAR(30) NOT NULL, studentid VARCHAR(10) NOT NULL, attemptid INT NOT NULL, score INT NOT NULL)";
            $result = mysqli_query($conn, $query);
        }

        //determines the number of attempts that have been made.
        $attemptid = 1;
        if($result)
        {
            while ($row = mysqli_fetch_assoc($result))
            {
                $attemptid = $row["attemptid"] + 1;
            }
        }

        //checks whether the number of attempts made already is less than 2
        if($attemptid > 2)
        {
            $errMsg .= "<p>You have already 2 attempts and are not allowed to make any more.</p>";
        }

        //checks whether there are any pending error messages and halts execution if there are.
        if($errMsg != "")
        {
            echo $errMsg;
            echo "<p>You can try again <a href=\"quiz.php\">here</a>.</p>";
        }
        else
        {
            $timestamp = time();
            $query = "INSERT into $sql_table  (date_time, firstname, lastname, studentid, attemptid, score) values ('$timestamp', '$firstname', '$lastname', '$studentid', '$attemptid', '$score')";
            $result = mysqli_query($conn, $query);

            //checks if the execution was successful
            if(!$result)
            {
                echo "<p class=\"wrong\">Something is wrong with ", $query, "</p>";
                //would not show up in a production script
            }
            else
            {
                //display an operation successful message
                echo "<p> class=\"ok\">Successfuly added attempt</p>";

                //Display attempt details
                echo "<table border=\"1\">\n";
                echo "<tr>\n "
                    ."<th scope=\"col\">First Name</th>\n "
                    ."<th scope=\"col\">Last Name</th>\n "
                    ."<th scope=\"col\">Student ID</th>\n "
                    ."<th scope=\"col\">Attempt Score</th>\n "
                    ."<th scope=\"col\">Attempt Count</th>\n "
                    ."</tr>\n ";

                echo "<tr>\n "
                    ."<td>", $firstname, "</td>\n"
                    ."<td>", $lastname, "</td>\n"
                    ."<td>", $studentid, "</td>\n"
                    ."<td>", $score, "%</td>\n"
                    ."<td>", $attemptid, "</td>\n"
                    ."</tr>\n";
                
                echo "</table>\n ";

                if(attemptid < 2)
                {
                    echo "<p>You can make a second attempt <a href=\"quiz.php\">here</a>.</p>";
                }
            }

            //Frees up the memory, after using the result pointer
            mysqli_free_result($result);
        }
        
        //close the database connection
        mysqli_close($conn);
    } //if successful database connection
    ?>
</body>
</html>